### PR TITLE
Adding Japanese translation

### PR DESCRIPTION
**Pull request by SiraKen**
This is my first contribution to an open source project on GitHub.
If something is wrong, please tell me.
I'm familiar with the music well, but I tried to translate it as far as I know.

I want to ask you one thing.
What is "ping-pong scale practice" mean? I couldn't find the appropriate translations in Japanese.

### CODE REVIEW

**Comment by ZaneH** [comment]
Ping pong means like back and forth

This is great 🙏

**Comment by SiraKen** [comment]
Thanks! Now I know what "ping pong" means.
So... does that mean going back and forth between scales or repetitive practice?

If there is no suitable expression in Japanese, I will try to add a short explanation on a new line using `\n`.

And I noticed that "Open settings" was not translated. Is this need to be fixed?
https://github.com/ZaneH/piano-trainer/blob/22960c7554cae7f5fc49899399656f3758caa7dc/src/components/Trainer/TrainerDisplay.tsx#L136-L138

**Comment by ZaneH** [comment]
> Thanks! Now I know what "ping pong" means. So... does that mean going back and forth between scales or repetitive practice?
> 
> If there is no suitable expression in Japanese, I will try to add a short explanation on a new line using `\n`.
> 
> And I noticed that "Open settings" was not translated. Is this need to be fixed?
> 
> https://github.com/ZaneH/piano-trainer/blob/22960c7554cae7f5fc49899399656f3758caa7dc/src/components/Trainer/TrainerDisplay.tsx#L136-L138

Checkout the [video here](https://vimeo.com/730642802) @ 1:13

It basically lets you practice going "back down" the scale instead of starting back at C4. Good catch on the "Open settings" translation, I'll be sure to fix it!

**Comment by SiraKen** [comment]
I got it! Now I consider the Japanese translation and will add it.
Thank you for telling me about Ping pong mode and fixing the "Open settings" part 🙏

**Pull request merged**
